# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('telegram_id', models.IntegerField()),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Registration')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-name'],
            },
        ),
    ]
