# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_editor', '0003_auto_20170502_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='passes',
            field=models.IntegerField(default=0),
        ),
    ]
