# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll_editor', '0004_auto_20170502_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=8, unique=True, verbose_name='Code'),
        ),
    ]
