# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_editor', '0005_poll_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='key',
            new_name='code',
        ),
    ]
